### ISSUE TITLE
[FEATURE REQUEST] Create a release per version/date

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spam-Domains-List#10]
Create a release in this repo per version/date whenever the links get updated.

**Comment by ThioJoe** [comment]
Considering the frequency I expect to update this, I think this would be very time consuming. Though I will look into ways to automating it, because it would make it much simpler to check for updates

**Comment by KendallDoesCoding** [comment]
> Considering the frequency I expect to update this, I think this would be very time consuming. Though I will look into ways to automating it, because it would make it much simpler to check for updates

Yeah, that's true. It will be time consuming.

**Comment by ThioJoe** [comment]
I got it working with a GitHub action, so now every time I update the spam text file it creates a new release named and tagged with the date

**Comment by KendallDoesCoding** [comment]
> I got it working with a GitHub action, so now every time I update the spam text file it creates a new release named and tagged with the date

Wow! That's epic. Thanks
