### ISSUE TITLE
[FEATURE REQUEST] Invalid Site Template

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spam-Domains-List#13]
I wanted to add a issue template where people could report invalid sites, I was going to mention the precautions, like, We appreciate you contributing and helping, but for this you should use a VPN or a VM, if your going to help us out for your safety, so that people could report the scam links of sites that are down. But, most of those sites are disguised as game scams but are adult content, so idk if I should add this so please let me know @ThioJoe

**Comment by ThioJoe** [comment]
I definitely do not want to encourage anyone to visit these domains for any reason

**Comment by KendallDoesCoding** [comment]
> I definitely do not want to encourage anyone to visit these domains for any reason, regardless of the precautions.

I can agree.
