### ISSUE TITLE
One more scam link

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spam-Domains-List#29]
![image](https://user-images.githubusercontent.com/84712013/147874494-9e40533a-e0eb-45b0-a482-e29a382f6f8e.png)

**Comment by ThioJoe** [comment]
Bruh you can put them all in one issue or edit the issue

**Comment by ThioJoe** [comment]
Also going forward please include a direct link to the comments or at least the video they're on. For some of them I want to be able to see the whole comment or copy/paste them.

**Comment by KendallDoesCoding** [comment]
> Bruh you can put them all in one issue or edit the issue to add more.

Sorry, I thought it would be easier if you check them one by one, whenever your free. Will do this in future. Sorry again.

**Comment by KendallDoesCoding** [comment]
> Also going forward please include a direct link to the comments or at least the video they're on. For some of them I want to be able to see the whole comment or copy/paste them.

Will do.
