### ISSUE TITLE
[FEATURE REQUEST] Remove site from domain list if down using a Github app?

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spam-Domains-List#30]
A github app may be out there, to detect if the site linked in the .txt file is online or if its down, so you dont have to go through every domain every week or month and check, and so that no extra domains get inculded which are down. The github app, will create a issue saying the website is down, and a PR if possible removing that site from the list. 

I think this is a good idea.

**Comment by ThioJoe** [comment]
I'll keep this open as an idea. I could probably find somewhere that checks for expired website registrations. I'd probably just create a local python script to do all the work, since it probably would only need to be done every once in a while, so wouldn't be a big deal to do manually.

**Comment by ThioJoe** [comment]
Actually just added it to the wiki for possible new features so the issue doesn't need to stay open

**Comment by KendallDoesCoding** [comment]
@ThioJoe I think this is possible to get done via React? I'm not sure though

**Comment by KendallDoesCoding** [comment]
> @ThioJoe I think this is possible to get done via React? I'm not sure though

but python script also will work, i believe like you mentioned.

**Comment by iam-py-test** [comment]
Sorry for posting on an old issue (can delete comment if that's not allowed), I wonder if [PyFunceble](https://github.com/funilrys/PyFunceble) would work?
Thanks
