### ISSUE TITLE
No scam-domain label

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spam-Domains-List#33]
The ISSUE_TEMPLATE to report scam links calls out the label scam-domain, but it doesnt exist in this repo.

**Comment by ThioJoe** [comment]
ok just fixed it

**Comment by KendallDoesCoding** [comment]
> ok just fixed it

Thanks

**Comment by KendallDoesCoding** [comment]
It works now, as expected.
