### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spam-Domains-List#34]
https://github.com/ThioJoe/YT-Spammer-Purge/discussions/316

**Comment by ThioJoe** [comment]
It's not for YouTube account usernames, it's for spammers who mention stuff like "contact [whatever username] on instagram for hacks" and stuff

**Comment by KendallDoesCoding** [comment]
> It's not for YouTube account usernames, it's for spammers who mention stuff like "contact [whatever username] on instagram for hacks" and stuff

Oh ok makes sense!
