### ISSUE TITLE
Scam Account Submission

### ISSUE THREAD

**Issue by ccuser44** [ThioJoe/YT-Spam-Domains-List#54]
### Duplicate Submissions

- [X] Yes, I checked that the account name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=C0ccBy8mxkg&lc=Ugwla2Jdf4obqXgCR-V4AaABAg
https://www.youtube.com/watch?v=C0ccBy8mxkg&lc=UgzzVJjYvxJ7eQkHQgZ4AaABAg
https://www.youtube.com/watch?v=C0ccBy8mxkg&lc=Ugy8k0UPt-n1ElRHFe54AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgxTWMvoxJrvrbRMCGJ4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=Ugz1ZFdnHkZwSksK2Zd4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgwJmZ4a-LFgBHe2EUx4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgwzH7TR5C9cjFS6Qn94AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgwhBCxMEuToTBesGdF4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgweedmWbQXrjHuxlJ94AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgzbRT1L55WsIbQ55PN4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgzXJploo3YxDZpVcnJ4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=Ugw_DeNItYmlHuB2xAF4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgzY8FL7Wax9OWrkFYR4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgzgYSU34vj553mlAp54AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgxEgK90ZuUK7pazCaJ4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgzmDmEipWyCzg9gafl4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgxlpXcAFQlYnAplHZ14AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=Ugz9M4d-DECppwwdr4B4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgyDnrg8dEPgdT-fmnx4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgwcPcp2goH0XWtdtiV4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgxBDWJJT1QXUlEx0T14AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=Ugxsdcyns3uYNYPSPkZ4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgwD2vbwIU4ptgeg5Xp4AaABAg
https://www.youtube.com/watch?v=FS9hSldLZhc&lc=UgyM2SgKFFg6cU8bn-Z4AaABAg

### (Optional) Screenshot of comments referencing the scam account

![Scam1](https://user-images.githubusercontent.com/68124053/148101118-7a5a60f4-dfe2-4c55-a99d-b0e98108e27e.PNG)
![Scam2](https://user-images.githubusercontent.com/68124053/148101122-788f29c9-7a53-4219-aba9-850f9b39cf50.PNG)
![Scam3](https://user-images.githubusercontent.com/68124053/148101341-da59faf0-d5b7-4765-80a6-fd80fcb18ece.PNG)
![Scam4](https://user-images.githubusercontent.com/68124053/148101672-0940f9d1-6872-4f19-9c90-f22ccaf3dc04.PNG)
![Scam5](https://user-images.githubusercontent.com/68124053/148102034-038c7ad6-dc8e-4906-96ab-f38bcb4cd6c8.PNG)
![Scam6](https://user-images.githubusercontent.com/68124053/148102778-22b79776-357e-43a1-952e-a1c68221c52a.PNG)
![Scam7](https://user-images.githubusercontent.com/68124053/148103175-f705a4ca-36ac-4dad-b40e-4a58136d95c1.PNG)
![Scam8](https://user-images.githubusercontent.com/68124053/148105969-b297ee68-53fb-4ecb-85aa-a15a0bfbaec3.PNG)
![Scam9](https://user-images.githubusercontent.com/68124053/148104289-c1154b78-0502-4e30-b1e8-d169cfd70824.PNG)
![Scam10](https://user-images.githubusercontent.com/68124053/148105978-c9912656-c96a-4e4c-ab05-7653c2e22cd4.PNG)
![Scam11](https://user-images.githubusercontent.com/68124053/148106200-3e18b09a-fa01-4e7a-8483-9f91d62e03c1.PNG)
![Scam12](https://user-images.githubusercontent.com/68124053/148106703-786648df-2985-44c6-9209-8b5b74d230fb.PNG)
![Scam13](https://user-images.githubusercontent.com/68124053/148109344-a4e4dd99-4c57-4060-a20f-bc28bf1da3c6.PNG)
![Scam14](https://user-images.githubusercontent.com/68124053/148109512-b1e06397-4a1b-4fac-8e44-2f8c1137d8fd.PNG)
![Scam15](https://user-images.githubusercontent.com/68124053/148109672-2b7dc27c-1dfd-4c8e-96b1-b788758752f1.PNG)
![Scam16](https://user-images.githubusercontent.com/68124053/148109874-1f19e0bd-f323-4193-bf6b-59749ffc5328.PNG)
![Scam17](https://user-images.githubusercontent.com/68124053/148109996-e29fa8e5-14e6-45c8-9fd3-3cf24496a015.PNG)
![Scam18](https://user-images.githubusercontent.com/68124053/148110133-7affc5c1-5a2d-4603-9eb1-88db755c2d46.PNG)
![Scam19](https://user-images.githubusercontent.com/68124053/148110298-c3ca7cb5-f650-4857-87af-56722f22a7c6.PNG)
![Scam20](https://user-images.githubusercontent.com/68124053/148110424-52920ea1-da37-4a7f-8d9d-d73f1f9a98c0.PNG)
![Scam21](https://user-images.githubusercontent.com/68124053/148110966-09172aa0-eb42-46bc-bcf3-e99fc0e63d0b.PNG)
![Scam22](https://user-images.githubusercontent.com/68124053/148110980-0603d447-0272-49bf-af01-b0a84cb3c175.PNG)
![Scam23](https://user-images.githubusercontent.com/68124053/148111000-7b26ae76-9cfa-4312-87e0-46b7c4313cdb.PNG)
![Scam24](https://user-images.githubusercontent.com/68124053/148111338-c7116b43-c358-40f7-a9dc-79e9ee2fbc45.PNG)
![Scam25](https://user-images.githubusercontent.com/68124053/148111349-5fa5df3c-6e6e-4572-94a5-c8027a36e20e.PNG)

### (Required) List of the scam account names

Trade with 👉@HACKERFUCCE0 ON TELEGRAM
⭕️ ROBUX GIVEAWAY CHECK MY CHANNEL⭕️
GET FREE ROBUX NOW CHECK MY CHANNEL
🔥 GET FREE ROBUX CHECK MY CHANEL 🔥
❤️ Claim 60k Robux Visit My.Channel j❤️
❤️ GET FREE ROBUX CHECK MY CHANEL ❤️
❤️ Get Free Robux Visit My Channel ❤️
‼️ CLAIM 50K ROBUX - CHECK MY CHANNEL ‼️
❤️ Claim Free Robux - Visit My Channel ❤️
🍀 CLAIM 10K VBUCKS - CHECK MY CHANNEL 🍀
check it ❤️ RBXR.MONSTER
⭐️ CLAIM 50k ROBUX - CHECK MY CHANNEL ⭐️
🟠 CLAIM 50k ROBUX - CHECK MY CHANNEL 🟠
❌ GET FREE ROBUX - CHECK MY CHANEL ❌
🟢 CLAIM 50k ROBUX - CHECK MY CHANNEL 🟢
Get Free Robux - Check my Channel
🩸 CLAIM 50k ROBUX - CHECK MY CHANNEL 🩸
❤️ Get Free Robux Check My Channel ❤️
OBTAIN FREE ROBUX HERE 👉 𝐆𝐄𝐓𝐑𝐗.𝐁𝐄𝐒𝐓 👈
❤️ Claim Free Robux Visit My Channel ❤️
GET FREE ROBUX HERE 👉 𝗚𝗘𝗧𝗥𝗫.𝗕𝗘𝗦𝗧 👈
⚫️ CLAIM 50k ROBUX - CHECK MY CHANNEL ⚫️
ROBUX? CHECK MY CHANNEL
❤️ GET FREE GIFT CARDS - CHECK MY CHANNEL ❤️
⭕️ Get 50k Robux - CHECK MY CHANNEL ⭕️

**Comment by ThioJoe** [comment]
Appreciate this, i'll look through and add them later. 

For future reference though, when I say username of the scam account, I don't mean the channel name of the youtube commenter, I mean the account name the spam comment directs users to contact. For example in the first one, the scam account is "HACKERFUCCE0". Likewise, many of these should instead be categorized as domain submissions
