### ISSUE TITLE
2 more spam links

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spam-Domains-List#9]
In this video (in 2020, these bots may still be around or gone but idk) a bunch of scam links are mentioned

https://www.youtube.com/watch?v=AllETPgeGKY

**Comment by KendallDoesCoding** [comment]
Links (DO NOT GO TO THESE SITES):
lucky-dating.online
activedating-24.online

**Comment by ThioJoe** [comment]
Yea the first one looks like it's already expired, the second one is still active though. Not sure if it's worth adding domains that were used a long time ago, considering they probably burn through these quickly

**Comment by ThioJoe** [comment]
added

**Comment by KendallDoesCoding** [comment]
> Yea the first one looks like it's already expired, the second one is still active though. Not sure if it's worth adding domains that were used a long time ago, considering they probably burn through these quickly

True.. I mostly added the links which were used for these bots recently in my PR though.
